import { createElement } from 'react'
import { act, create, type ReactTestInstance, type ReactTestRenderer } from 'react-test-renderer'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { ComponentPrototypeMetadata, ToolBlock } from '../../agent/types'
import {
  ComponentPrototypeCard,
  componentPrototypeFollowUpPrompt,
  componentPrototypeFrameSize,
  componentPrototypeFromBlock
} from './ComponentPrototypeCard'

const actionMocks = vi.hoisted(() => ({
  previewWorkspaceFile: vi.fn(),
  readWorkspaceFile: vi.fn(),
  writeText: vi.fn()
}))

vi.mock('../../lib/workspace-file-preview', () => ({
  previewWorkspaceFile: actionMocks.previewWorkspaceFile
}))

vi.mock('../design/DesignHtmlPreviewHost', async () => {
  const { createElement } = await import('react')
  return {
    DesignHtmlPreviewHost: ({ children, ...props }: Record<string, unknown>) => createElement(
      'section',
      { 'data-preview-host': true, ...props },
      (children as (value: {
        state: { webviewUrl: string; error: string }
        renderWebview: (props: Record<string, unknown>) => ReturnType<typeof createElement>
      }) => ReturnType<typeof createElement>)({
        state: { webviewUrl: 'file:///workspace/prototype.html', error: '' },
        renderWebview: (webviewProps) => createElement('div', {
          ...webviewProps,
          'data-prototype-webview': true
        })
      })
    )
  }
})

vi.mock('react-i18next', () => {
  const labels: Record<string, string> = {
    componentPrototypeFailed: 'Generation failed',
    componentPrototypeDesigning: 'Designing',
    componentPrototypeInteractive: 'Interactive',
    componentPrototypeDesktop: 'Desktop',
    componentPrototypeMobile: 'Mobile',
    componentPrototypeRefresh: 'Refresh prototype',
    componentPrototypeCopyCode: 'Copy prototype code',
    componentPrototypeLoadFailed: 'The prototype could not be loaded.',
    componentPrototypeMainAgent: 'Kun',
    componentPrototypeSubagent: 'Design Sub-agent',
    componentPrototypeGeneratedByMainAgent: 'Published directly by Kun',
    componentPrototypeGeneratedBy: 'Generated by Design Sub-agent',
    componentPrototypeViewCode: 'View code',
    componentPrototypeIterate: 'Continue adjusting',
    componentPrototypeAdopt: 'Adopt design',
    browserMore: 'More'
  }
  return {
    useTranslation: () => ({
      t: (key: string) => labels[key] ?? key,
      i18n: { language: 'zh-CN', resolvedLanguage: 'zh-CN' }
    })
  }
})

const metadata: ComponentPrototypeMetadata = {
  version: 1,
  status: 'completed',
  artifactId: 'component_date_picker',
  title: 'Date range picker',
  relativePath: '.kun-design/component-prototypes/date-picker/prototype.html',
  viewport: { width: 760, height: 520 },
  producer: 'component-designer',
  profile: 'component-designer',
  byteSize: 12_400,
  contentHash: 'a'.repeat(64)
}

function block(componentPrototype: ComponentPrototypeMetadata = metadata): ToolBlock {
  return {
    kind: 'tool',
    id: 'tool_component',
    summary: 'design_component',
    status: componentPrototype.status === 'failed' ? 'error' : 'success',
    toolKind: 'file_change',
    meta: { toolName: 'design_component', componentPrototype }
  }
}

function instanceText(instance: ReactTestInstance): string {
  return instance.children.map((child) => typeof child === 'string' ? child : instanceText(child)).join('')
}

describe('ComponentPrototypeCard metadata helpers', () => {
  it('accepts the versioned component artifact but rejects unsafe paths and viewports', () => {
    expect(componentPrototypeFromBlock(block())).toEqual(metadata)
    expect(componentPrototypeFromBlock(block({
      ...metadata,
      relativePath: '.kun-design/component-prototypes/../secret/prototype.html'
    }))).toBeNull()
    expect(componentPrototypeFromBlock(block({
      ...metadata,
      viewport: { width: 2_000, height: 520 }
    }))).toBeNull()
  })

  it('normalizes historical sub-agent metadata and accepts direct main-agent metadata', () => {
    const { producer: _producer, ...legacyMetadata } = metadata
    const legacyBlock = {
      ...block(),
      meta: { toolName: 'design_component', componentPrototype: legacyMetadata }
    } as ToolBlock
    expect(componentPrototypeFromBlock(legacyBlock)).toEqual(metadata)

    const direct = { ...metadata, producer: 'main-agent' as const, profile: undefined, childId: undefined }
    expect(componentPrototypeFromBlock(block(direct))).toEqual(direct)
  })

  it('clamps desktop/mobile frames and builds follow-up prompts around the artifact', () => {
    expect(componentPrototypeFrameSize(metadata, 'desktop')).toEqual({ width: '100%', height: 130 })
    expect(componentPrototypeFrameSize(metadata, 'mobile')).toEqual({ width: 360, height: 338 })
    expect(componentPrototypeFollowUpPrompt(metadata, 'iterate')).toContain(metadata.relativePath)
    expect(componentPrototypeFollowUpPrompt(metadata, 'adopt')).toContain('采纳')
    expect(componentPrototypeFollowUpPrompt(metadata, 'adopt', 'en')).toContain('Adopt')
  })
})

describe('ComponentPrototypeCard interactions', () => {
  let renderer: ReactTestRenderer
  const onPrompt = vi.fn()

  const openMenu = async (): Promise<void> => {
    await act(async () => renderer.root.findByProps({ 'aria-label': 'More' }).props.onClick())
  }

  const menuButton = (label: string): ReactTestInstance => {
    return renderer.root.findAllByType('button').find((button) => instanceText(button).includes(label))!
  }

  beforeEach(async () => {
    ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true
    actionMocks.previewWorkspaceFile.mockReset()
    actionMocks.readWorkspaceFile.mockReset().mockResolvedValue({ ok: true, content: '<html></html>' })
    actionMocks.writeText.mockReset().mockResolvedValue(undefined)
    onPrompt.mockReset()
    vi.stubGlobal('window', {
      kunGui: { readWorkspaceFile: actionMocks.readWorkspaceFile },
      setTimeout
    })
    vi.stubGlobal('navigator', { clipboard: { writeText: actionMocks.writeText } })
    await act(async () => {
      renderer = create(createElement(ComponentPrototypeCard, {
        block: block(),
        workspaceRoot: '/workspace',
        onPrompt
      }))
    })
  })

  afterEach(async () => {
    await act(async () => renderer.unmount())
    vi.unstubAllGlobals()
  })

  it('renders a centered compact surface and keeps secondary controls in one overflow menu', async () => {
    const card = renderer.root.findByProps({ 'data-component-prototype-id': metadata.artifactId })
    expect(card.props.className).toContain('mx-auto')
    expect(card.props.className).toContain('max-w-[600px]')
    expect(renderer.root.findByProps({ 'data-prototype-webview': true })).toBeTruthy()
    expect(renderer.root.findByType('header').props.className).toContain('h-8')
    expect(renderer.root.findByType('header').findAllByType('button')).toHaveLength(1)
    expect(renderer.root.findAllByProps({ 'data-component-prototype-menu': true })).toHaveLength(0)
    const host = renderer.root.findByProps({ 'data-preview-host': true })
    expect(host.props.partition).toBe('kun-component-prototype-tool_component')
    expect(host.props.workspaceRoot).toBe('/workspace')

    await openMenu()
    expect(renderer.root.findByProps({ 'data-component-prototype-menu': true })).toBeTruthy()
    await act(async () => menuButton('Mobile').props.onClick())
    expect(renderer.root.findAll((node) => node.props.style?.width === 360)).toHaveLength(1)

    const beforeRefresh = renderer.root.findByProps({ 'data-preview-host': true })
    await openMenu()
    await act(async () => menuButton('Refresh prototype').props.onClick())
    const afterRefresh = renderer.root.findByProps({ 'data-preview-host': true })
    expect(afterRefresh).not.toBe(beforeRefresh)
  })

  it('copies/views code and prefills the existing composer for iterate/adopt', async () => {
    await openMenu()
    await act(async () => {
      menuButton('Copy prototype code').props.onClick()
      await Promise.resolve()
    })
    expect(actionMocks.readWorkspaceFile).toHaveBeenCalledWith({
      path: metadata.relativePath,
      workspaceRoot: '/workspace'
    })
    expect(actionMocks.writeText).toHaveBeenCalledWith('<html></html>')

    await openMenu()
    await act(async () => menuButton('View code').props.onClick())
    expect(actionMocks.previewWorkspaceFile).toHaveBeenCalledWith({
      path: metadata.relativePath,
      workspaceRoot: '/workspace'
    })
    await openMenu()
    await act(async () => menuButton('Continue adjusting').props.onClick())
    await openMenu()
    await act(async () => menuButton('Adopt design').props.onClick())
    expect(onPrompt).toHaveBeenNthCalledWith(1, expect.stringContaining('继续调整'))
    expect(onPrompt).toHaveBeenNthCalledWith(2, expect.stringContaining('采纳'))
  })

  it('labels direct prototypes as published by Kun instead of a design sub-agent', async () => {
    const direct = { ...metadata, producer: 'main-agent' as const, profile: undefined, childId: undefined }
    await act(async () => renderer.update(createElement(ComponentPrototypeCard, {
      block: block(direct),
      workspaceRoot: '/workspace',
      onPrompt
    })))

    expect(JSON.stringify(renderer.toJSON())).not.toContain('Design Sub-agent')
    await openMenu()
    expect(JSON.stringify(renderer.toJSON())).toContain('Kun')
    expect(renderer.root.findByProps({ title: 'Published directly by Kun' })).toBeTruthy()
  })

  it('shows a bounded failure state and disables follow-up actions', async () => {
    await act(async () => renderer.update(createElement(ComponentPrototypeCard, {
      block: block({ ...metadata, status: 'failed', error: 'The child returned remote resources.' }),
      workspaceRoot: '/workspace',
      onPrompt
    })))

    expect(JSON.stringify(renderer.toJSON())).toContain('The child returned remote resources.')
    expect(renderer.root.findAllByProps({ 'data-prototype-webview': true })).toHaveLength(0)
    await openMenu()
    const followUps = [menuButton('Continue adjusting'), menuButton('Adopt design')]
    expect(followUps.every((button) => button.props.disabled === true)).toBe(true)
  })
})
